bundler_args: --without development
language: ruby
rvm:
  - jruby-19mode
  - rbx-19mode
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
matrix:
  allow_failures:
    - rvm: rbx-19mode
env:
  - TEST_DOTIDE_LOGIN="test" TEST_DOTIDE_PASSWORD="useintest" TEST_DOTIDE_AUTH_TOKEN="8881da61149b75a0b7b4f2eb53ce4d9d"
before_script:
  - chmod 600 spec/fixtures/.netrc
