bundler_args: --without development
language: ruby
rvm:
  - jruby-19mode
  - rbx-19mode
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
matrix:
  allow_failures:
    - rvm: rbx-19mode
env:
  - TEST_DOTIDE_CLIENT_ID="e71475ae1f196651f50b" TEST_DOTIDE_CLIENT_SECRET="0be8f51f88a037114bba6c91b805fabc874fde22" TEST_DOTIDE_ACCESS_TOKEN="28b0f51814c8a441460ea97efcd7d44ab0548d5b6b9403f4db9eb4b820844205"
before_script:
  - chmod 600 spec/fixtures/.netrc
